# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
    - main
    - dev
    - nightly

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
      - name: Build docs
      - run: npm install
      - run: npm run docs
      - name: Set up Git
        run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
      - name: Commit
        run: |
            git pull
            git add .
            git commit -m "Build docs"
            git push
