name: Gen Docs

on:
    push:
        branches: [main, dev, nightly]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build docs
              run: |
                  npm install
                  sudo npm docs
            - name: setup git config
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"
            - name: commit
              run: |
                  git pull
                  git add .
                  git commit -m "Gen Docs"
                  git push
